language: php

php:
    - 7.2

before_install:
  - git clone https://github.com/akeneo/pim-community-dev.git
  - composer install

script:
  - ./src/inspectors/phpmetrics.sh
  - ./src/inspectors/phpstan.sh
  - ./src/inspectors/scrutinizer.sh
  - ./src/inspectors/sonarcube.sh
