language: php

php:
    - 7.2

addons:
  sonarcloud:
    organization: "tamarasaurus-github"
    token:
      secure: $SONAR_TOKEN

before_install:
  - git clone https://github.com/tamarasaurus/pim-community-dev.git
  - cd pim-community-dev && git checkout $COMMIT
  - COMPOSER_MEMORY_LIMIT=-1 composer require phpmetrics/phpmetrics
  - cd ../

script:
  - ./src/inspectors/phpmetrics.sh
  - ./src/inspectors/phpstan.sh
  - ./src/inspectors/scrutinizer.sh
  - sonar-scanner -Dsonar.projectKey=tamarasaurus_pim-community-dev -Dsonar.projectBaseDir=pim-community-dev -Dsonar.analysis.commit=$COMMIT -Dsonar.analysis.user=$USER
