language: php

php:
    - 7.2

addons:
  sonarcloud:
    organization: "tamarasaurus-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

before_install:
  - git clone https://github.com/tamarasaurus/pim-community-dev.git
  - cd pim-community-dev && git checkout $COMMIT
  - cd ../
  - composer install

script:
  - ./src/inspectors/phpmetrics.sh
  - ./src/inspectors/phpstan.sh
  - ./src/inspectors/scrutinizer.sh
  # - ./src/inspectors/sonarcube.sh
  - sonar-scanner -Dsonar.projectKey=tamarasaurus_pim-community-dev -Dsonar.projectBaseDir=pim-community-dev
